spring:
  application:
    name: outbox-worker

  datasource:
    url: jdbc:postgresql://localhost:5433/banking
    username: banking
    password: banking
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  rabbitmq:
    host: localhost
    port: 5672
    username: banking
    password: banking

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
