services:

  postgresql:
    image: postgres:16
    container_name: banking-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: banking
      POSTGRES_DB: banking
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: banking-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: banking
      RABBITMQ_DEFAULT_PASS: banking

volumes:
  pgdata:
