spring:
  application:
    name: account-api

  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: banking
    password: banking
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
